### PR TITLE
pass wget call to subprocess as list

### PR DESCRIPTION
**Pull request by dionhaefner**
The original version wouldn't work on Linux-based systems. In my tests, this version worked on both Windows and Linux.

### CODE REVIEW

**Comment by dionhaefner** [comment]
Also fixes #1, I guess,

**Comment by dionhaefner** [comment]
Seems like the Trusty-``wget`` has no ``hsts-file`` option. The tests run successfully on Xenial (Ubuntu 16.04).

**Comment by mrpgraae** [comment]
Then Trusty uses wget 1.15 (https://packages.ubuntu.com/trusty/wget).
`--hsts-file` was added in 1.17 (https://savannah.gnu.org/forum/forum.php?forum_id=8410)

**Comment by mrpgraae** [comment]
But Trusty is practically _ancient_ 😄, so maybe it's fine. There's a new LTS version at least.

**Comment by j08lue** [comment]
I frankly don't know why I added the `--hsts-file` thing at all. It was for some reason, though... One of the servers wanted it, maybe SWI to obscure their interface. Judging from the logs it seems not to work on Windows either. Would you mind testing whether it is needed at all? Test with the SWI download, as this is actually the only place where we still use `wget_provider`.

**Comment by dionhaefner** [comment]
Works on both platforms.

**Comment by j08lue** [comment]
OK then let us just merge this now. I hope we will soon get rid of the `wget_provider` altogether.

**Comment by j08lue** [comment]
Oh, and thanks.

**Pull request merged**
